name: percon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1  
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.3.0
  google_sign_in: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.0
  get_it: ^7.6.7

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/travels.json
  
  # Localization
  generate: true
